server:
  port: 8080
  tomcat:
    max-threads: 800
    url-encoding: UTF-8

logging:
    file: springBootRabbitmq.log
    path: /var/log

spring:
    profiles:
        active: dev
    rabbitmq:
      host: docker1.cd121.cc
      port: 5672
      username: spy
      password: shipengyan
      virtual-host: /

